name: Altın Fiyatlarını Güncelle

on:
  schedule:
    - cron: '0 * * * *'   # Her saat başı
  workflow_dispatch:       # Manuel tetikleme

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu Çek
        uses: actions/checkout@v3

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Altın Fiyatlarını Güncelle
        run: |
          curl -s https://finans.truncgil.com/today.json -o data.json
          node -e "
          const fs = require('fs');
          const data = require('./data.json');
          const altin = {
            gram: { al: data['Gram Altın']['Alış'], sat: data['Gram Altın']['Satış'] },
            ceyrek: { al: data['Çeyrek Altın']['Alış'], sat: data['Çeyrek Altın']['Satış'] },
            yarim: { al: data['Yarım Altın']['Alış'], sat: data['Yarım Altın']['Satış'] },
            ons: { al: data['Ons']['Alış'], sat: data['Ons']['Satış'] }
          };
          fs.writeFileSync('altin.json', JSON.stringify(altin, null, 2), 'utf-8');
          "

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add altin.json
          git commit -m "Altın fiyatları güncellendi [Node.js]" || echo "Değişiklik yok"
          git push
