name: Altın Fiyat Güncelle
on:
  schedule:
    - cron: '*/10 * * * *'   # Her 10 dakikada bir çalışacak
  workflow_dispatch:          # Manuel çalıştırma seçeneği

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gereksinimleri yükle
        run: pip install requests

      - name: altin.json'u güncelle
        run: python update_altin.py

      - name: Değişiklikleri commit ve push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add altin.json
          git commit -m "Otomatik altın fiyat güncellemesi"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
