name: Altın Fiyat Güncelle

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests
      - run: python update_altin.py
      - run: git config --global user.name "adahanN22"
      - run: git config --global user.email "adahan@example.com"
      - run: git add altin.json
      - run: git commit -m "Update altin.json" || echo "No changes"
      - run: git push
